import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CloukitDropoutModule } from '@cloukit/dropout';
import { CloukitThemeModule } from '@cloukit/theme';
import { CloukitTooltipModule } from '../index';
import { DemoComponent } from './demo.component';
import { CloukitStoryModule, CloukitStoryService } from '@cloukit/story';
import { Story00Component } from 'demo/stories/story-00-tooltip-directions';
import { Story01Component } from './stories/story-01-trigger-element-destroyed';


@NgModule({
  declarations: [
    DemoComponent,
    Story00Component,
    Story01Component,
  ],
  exports: [ DemoComponent ],
  imports: [
    CommonModule,
    CloukitThemeModule,
    CloukitDropoutModule,
    CloukitTooltipModule,
    CloukitStoryModule,
  ],
  providers: [ ],
  bootstrap: [ ],
})
export class DemoModule {
  constructor(private cloukitStoryService: CloukitStoryService) {
    //
    // INITIALIZE STORY SOURCES
    //
    const baseUrl = document.getElementsByTagName('base')[0].href;
    const storySourceJsonUrl = `${baseUrl}assets/demoStoriesSource.json`; // File is auto generated by build chain!
    this.cloukitStoryService.loadStoryJson(storySourceJsonUrl);
  }
}
